
# Build Settings
# theme: jekyll-theme-minimal
theme: "minimal-mistakes-jekyll"
inlcude: ["_pages"]
title: "Cuerpos Cuerpos Cuerpos"
minimal_mistakes_skin: "neon"
title_separator: "|"
description: "Minimal blog on random topics."
