
# Build Settings
# theme: jekyll-theme-minimal
remote_theme: minimal-mistakes-jekyll
title: "Cuerpos Cuerpos Cuerpos"
minimal_mistakes_skin: "neon"
title_separator: "|"
description: "Minimal blog on random topics."
