
# Build Settings
# theme: jekyll-theme-minimal
#theme: "minimal-mistakes-jekyll"
remote_theme : "mmistakes/minimal-mistakes"
inlcude:
  - _pages
title: "Cuerpos Cuerpos Cuerpos"
minimal_mistakes_skin: "neon"
title_separator: "|"
description: "Minimal blog on random topics."
paginate: 5 # amount of posts to display
paginate_path: /blog/page:num/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
